# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# ReactNativeConfig
project 'sccReactNative',{
  'Debug' => :debug,
  'DebugSandbox' => :debug,
  'Release' => :release,
  'ReleaseSandbox' => :release,
}


target 'sccReactNative' do
  config = use_native_modules!

  pod 'NMapsMap'
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  pod 'SVGKit', :modular_headers => true
  pod 'CocoaLumberjack', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'sccReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    ENVFILES = {
      'Debug' => '$(PODS_ROOT)/../../subprojects/scc-frontend-build-configurations/production/.env',
      'DebugSandbox' => '$(PODS_ROOT)/../../subprojects/scc-frontend-build-configurations/sandbox/.env',
      'Release' => '$(PODS_ROOT)/../../subprojects/scc-frontend-build-configurations/production/.env',
      'ReleaseSandbox' => '$(PODS_ROOT)/../../subprojects/scc-frontend-build-configurations/sandbox/.env',
    }
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end

    # Xcode 14 부터 pod signing team 을 manually 넣어줘야 한다.
    # https://github.com/CocoaPods/CocoaPods/issues/1140://github.com/CocoaPods/CocoaPods/issues/11402
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGN_IDENTITY'] = ''
        end
      end
    end

    marker_file = File.join(installer.sandbox.root, 'SVGKit_fix_applied')
    unless File.exist?(marker_file)
      svgkit_path = File.join(installer.sandbox.pod_dir('SVGKit'), 'Source')
      Dir.glob(File.join(svgkit_path, '**', '*.{h,m}')).each do |file|
        FileUtils.chmod("u+w", file)

        text = File.read(file)
        new_contents = text.gsub('Node.h', 'SVGKit/Node.h')
        new_contents = new_contents.gsub('CSSValue.h', 'SVGKit/CSSValue.h')
        new_contents = new_contents.gsub('SVGLength.h', 'SVGKit/SVGLength.h')
        File.open(file, 'w') { |f| f.write(new_contents) }
      end

      FileUtils.touch(marker_file)
      puts "Post install script completed and marker file created"
    else
      puts "Marker file exists, skipping post install script"
    end
  end
end
