package club.staircrusher

import com.naver.maps.geometry.LatLng
import com.naver.maps.map.overlay.OverlayImage

data class MarkerData(
    val location: LatLng,
    val id: String,
    val displayName: String,
    val iconResource: String,
) {
    fun getIcon(isSelected: Boolean): OverlayImage {
        val type = iconResource.split("_")[0]
        val level = iconResource.split("_")[1]
        return map[Triple(type, level, isSelected)] ?: OverlayImage.fromResource(R.drawable.default_none_off)
    }
    private val map = mapOf(
        Triple("cafe", "0", false) to OverlayImage.fromResource(R.drawable.cafe_0_off),
        Triple("cafe", "0", true) to OverlayImage.fromResource(R.drawable.cafe_0_on),
        Triple("cafe", "1", false) to OverlayImage.fromResource(R.drawable.cafe_1_off),
        Triple("cafe", "1", true) to OverlayImage.fromResource(R.drawable.cafe_1_on),
        Triple("cafe", "2", false) to OverlayImage.fromResource(R.drawable.cafe_2_off),
        Triple("cafe", "2", true) to OverlayImage.fromResource(R.drawable.cafe_2_on),
        Triple("cafe", "3", false) to OverlayImage.fromResource(R.drawable.cafe_3_off),
        Triple("cafe", "3", true) to OverlayImage.fromResource(R.drawable.cafe_3_on),
        Triple("cafe", "4", false) to OverlayImage.fromResource(R.drawable.cafe_4_off),
        Triple("cafe", "4", true) to OverlayImage.fromResource(R.drawable.cafe_4_on),
        Triple("cafe", "5", false) to OverlayImage.fromResource(R.drawable.cafe_5_off),
        Triple("cafe", "5", true) to OverlayImage.fromResource(R.drawable.cafe_5_on),
        Triple("cafe", "none", false) to OverlayImage.fromResource(R.drawable.cafe_none_off),
        Triple("cafe", "none", true) to OverlayImage.fromResource(R.drawable.cafe_none_on),
        Triple("cafe", "progress", false) to OverlayImage.fromResource(R.drawable.cafe_progress_off),
        Triple("cafe", "progress", true) to OverlayImage.fromResource(R.drawable.cafe_progress_on),

        Triple("conv", "0", false) to OverlayImage.fromResource(R.drawable.conv_0_off),
        Triple("conv", "0", true) to OverlayImage.fromResource(R.drawable.conv_0_on),
        Triple("conv", "1", false) to OverlayImage.fromResource(R.drawable.conv_1_off),
        Triple("conv", "1", true) to OverlayImage.fromResource(R.drawable.conv_1_on),
        Triple("conv", "2", false) to OverlayImage.fromResource(R.drawable.conv_2_off),
        Triple("conv", "2", true) to OverlayImage.fromResource(R.drawable.conv_2_on),
        Triple("conv", "3", false) to OverlayImage.fromResource(R.drawable.conv_3_off),
        Triple("conv", "3", true) to OverlayImage.fromResource(R.drawable.conv_3_on),
        Triple("conv", "4", false) to OverlayImage.fromResource(R.drawable.conv_4_off),
        Triple("conv", "4", true) to OverlayImage.fromResource(R.drawable.conv_4_on),
        Triple("conv", "5", false) to OverlayImage.fromResource(R.drawable.conv_5_off),
        Triple("conv", "5", true) to OverlayImage.fromResource(R.drawable.conv_5_on),
        Triple("conv", "none", false) to OverlayImage.fromResource(R.drawable.conv_none_off),
        Triple("conv", "none", true) to OverlayImage.fromResource(R.drawable.conv_none_on),
        Triple("conv", "progress", false) to OverlayImage.fromResource(R.drawable.conv_progress_off),
        Triple("conv", "progress", true) to OverlayImage.fromResource(R.drawable.conv_progress_on),

        Triple("rest", "0", false) to OverlayImage.fromResource(R.drawable.rest_0_off),
        Triple("rest", "0", true) to OverlayImage.fromResource(R.drawable.rest_0_on),
        Triple("rest", "1", false) to OverlayImage.fromResource(R.drawable.rest_1_off),
        Triple("rest", "1", true) to OverlayImage.fromResource(R.drawable.rest_1_on),
        Triple("rest", "2", false) to OverlayImage.fromResource(R.drawable.rest_2_off),
        Triple("rest", "2", true) to OverlayImage.fromResource(R.drawable.rest_2_on),
        Triple("rest", "3", false) to OverlayImage.fromResource(R.drawable.rest_3_off),
        Triple("rest", "3", true) to OverlayImage.fromResource(R.drawable.rest_3_on),
        Triple("rest", "4", false) to OverlayImage.fromResource(R.drawable.rest_4_off),
        Triple("rest", "4", true) to OverlayImage.fromResource(R.drawable.rest_4_on),
        Triple("rest", "5", false) to OverlayImage.fromResource(R.drawable.rest_5_off),
        Triple("rest", "5", true) to OverlayImage.fromResource(R.drawable.rest_5_on),
        Triple("rest", "none", false) to OverlayImage.fromResource(R.drawable.rest_none_off),
        Triple("rest", "none", true) to OverlayImage.fromResource(R.drawable.rest_none_on),
        Triple("rest", "progress", false) to OverlayImage.fromResource(R.drawable.rest_progress_off),
        Triple("rest", "progress", true) to OverlayImage.fromResource(R.drawable.rest_progress_on),

        Triple("phar", "0", false) to OverlayImage.fromResource(R.drawable.phar_0_off),
        Triple("phar", "0", true) to OverlayImage.fromResource(R.drawable.phar_0_on),
        Triple("phar", "1", false) to OverlayImage.fromResource(R.drawable.phar_1_off),
        Triple("phar", "1", true) to OverlayImage.fromResource(R.drawable.phar_1_on),
        Triple("phar", "2", false) to OverlayImage.fromResource(R.drawable.phar_2_off),
        Triple("phar", "2", true) to OverlayImage.fromResource(R.drawable.phar_2_on),
        Triple("phar", "3", false) to OverlayImage.fromResource(R.drawable.phar_3_off),
        Triple("phar", "3", true) to OverlayImage.fromResource(R.drawable.phar_3_on),
        Triple("phar", "4", false) to OverlayImage.fromResource(R.drawable.phar_4_off),
        Triple("phar", "4", true) to OverlayImage.fromResource(R.drawable.phar_4_on),
        Triple("phar", "5", false) to OverlayImage.fromResource(R.drawable.phar_5_off),
        Triple("phar", "5", true) to OverlayImage.fromResource(R.drawable.phar_5_on),
        Triple("phar", "none", false) to OverlayImage.fromResource(R.drawable.phar_none_off),
        Triple("phar", "none", true) to OverlayImage.fromResource(R.drawable.phar_none_on),
        Triple("phar", "progress", false) to OverlayImage.fromResource(R.drawable.phar_progress_off),
        Triple("phar", "progress", true) to OverlayImage.fromResource(R.drawable.phar_progress_on),

        Triple("hos", "0", false) to OverlayImage.fromResource(R.drawable.hos_0_off),
        Triple("hos", "0", true) to OverlayImage.fromResource(R.drawable.hos_0_on),
        Triple("hos", "1", false) to OverlayImage.fromResource(R.drawable.hos_1_off),
        Triple("hos", "1", true) to OverlayImage.fromResource(R.drawable.hos_1_on),
        Triple("hos", "2", false) to OverlayImage.fromResource(R.drawable.hos_2_off),
        Triple("hos", "2", true) to OverlayImage.fromResource(R.drawable.hos_2_on),
        Triple("hos", "3", false) to OverlayImage.fromResource(R.drawable.hos_3_off),
        Triple("hos", "3", true) to OverlayImage.fromResource(R.drawable.hos_3_on),
        Triple("hos", "4", false) to OverlayImage.fromResource(R.drawable.hos_4_off),
        Triple("hos", "4", true) to OverlayImage.fromResource(R.drawable.hos_4_on),
        Triple("hos", "5", false) to OverlayImage.fromResource(R.drawable.hos_5_off),
        Triple("hos", "5", true) to OverlayImage.fromResource(R.drawable.hos_5_on),
        Triple("hos", "none", false) to OverlayImage.fromResource(R.drawable.hos_none_off),
        Triple("hos", "none", true) to OverlayImage.fromResource(R.drawable.hos_none_on),
        Triple("hos", "progress", false) to OverlayImage.fromResource(R.drawable.hos_progress_off),
        Triple("hos", "progress", true) to OverlayImage.fromResource(R.drawable.hos_progress_on),

        Triple("default", "0", false) to OverlayImage.fromResource(R.drawable.default_0_off),
        Triple("default", "0", true) to OverlayImage.fromResource(R.drawable.default_0_on),
        Triple("default", "1", false) to OverlayImage.fromResource(R.drawable.default_1_off),
        Triple("default", "1", true) to OverlayImage.fromResource(R.drawable.default_1_on),
        Triple("default", "2", false) to OverlayImage.fromResource(R.drawable.default_2_off),
        Triple("default", "2", true) to OverlayImage.fromResource(R.drawable.default_2_on),
        Triple("default", "3", false) to OverlayImage.fromResource(R.drawable.default_3_off),
        Triple("default", "3", true) to OverlayImage.fromResource(R.drawable.default_3_on),
        Triple("default", "4", false) to OverlayImage.fromResource(R.drawable.default_4_off),
        Triple("default", "4", true) to OverlayImage.fromResource(R.drawable.default_4_on),
        Triple("default", "5", false) to OverlayImage.fromResource(R.drawable.default_5_off),
        Triple("default", "5", true) to OverlayImage.fromResource(R.drawable.default_5_on),
        Triple("default", "none", false) to OverlayImage.fromResource(R.drawable.default_none_off),
        Triple("default", "none", true) to OverlayImage.fromResource(R.drawable.default_none_on),
        Triple("default", "progress", false) to OverlayImage.fromResource(R.drawable.default_progress_off),
        Triple("default", "progress", true) to OverlayImage.fromResource(R.drawable.default_progress_on),

        Triple("toilet", "0", false) to OverlayImage.fromResource(R.drawable.toilet_0_off),
        Triple("toilet", "0", true) to OverlayImage.fromResource(R.drawable.toilet_0_on),
        Triple("toilet", "5", false) to OverlayImage.fromResource(R.drawable.toilet_5_off),
        Triple("toilet", "5", true) to OverlayImage.fromResource(R.drawable.toilet_5_on),
        Triple("toilet", "none", false) to OverlayImage.fromResource(R.drawable.toilet_none_off),
        Triple("toilet", "none", true) to OverlayImage.fromResource(R.drawable.toilet_none_on),
    )
}
