name: Native Build Deployment

on:
  push:
    tags:
      - 'v*-android'
      - 'v*-ios'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build (android or ios)'
        required: true
        type: choice
        options:
          - android
          - ios
      scheme:
        description: 'Build scheme (sandbox or production)'
        required: true
        type: choice
        options:
          - sandbox
          - production

jobs:
  android:
    if: startsWith(github.ref_name, 'v') && endsWith(github.ref_name, '-android') || (github.event_name == 'workflow_dispatch' && github.event.inputs.platform == 'android')
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SCC_FRONTEND_BUILD_CONFIGURATIONS_SSH_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install JavaScript dependencies
        run: yarn install --immutable

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: android

      - name: Run Android release candidate
        run: |
          cd android
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            bundle exec fastlane android release_candidate scheme:${{ github.event.inputs.scheme }} skip_version_update:true
          else
            bundle exec fastlane android release_candidate scheme:sandbox skip_version_update:true
          fi

      # - name: Notify Slack on Success
      #   if: success()
      #   run: |
      #     CURRENT_GITHUB_ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #     curl -X POST -H 'Content-type: application/json' --data "{\"attachments\":[{\"color\":\"#0000FF\",\"title\":\"[NATIVE] Android Build Deployment Successful\", \"text\":\"Tag: ${{ github.ref_name }} (<$CURRENT_GITHUB_ACTION_RUN_URL|github action run url>)\"}]}" ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }}

      # - name: Notify Slack on Failure
      #   if: failure()
      #   run: |
      #     CURRENT_GITHUB_ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #     curl -X POST -H 'Content-type: application/json' --data "{\"attachments\":[{\"color\":\"#FF0000\",\"title\":\"[NATIVE] Android Build Deployment Failed\", \"text\":\"<!subteam^S052B9WNGCV> Tag: ${{ github.ref_name }} (<$CURRENT_GITHUB_ACTION_RUN_URL|github action run url>)\"}]}" ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }}

  ios:
    if: startsWith(github.ref_name, 'v') && endsWith(github.ref_name, '-ios') || (github.event_name == 'workflow_dispatch' && github.event.inputs.platform == 'ios')
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SCC_FRONTEND_BUILD_CONFIGURATIONS_SSH_KEY }}

      - name: Setup SSH agent for build certificates
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SCC_BUILD_CERTIFICATES_SSH_KEY }}
            ${{ secrets.SCC_FRONTEND_BUILD_CONFIGURATIONS_SSH_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install JavaScript dependencies
        run: yarn install --immutable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: ios

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Run iOS release candidate
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          cd ios
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            bundle exec fastlane ios release_candidate scheme:${{ github.event.inputs.scheme }} skip_version_update:true
          else
            bundle exec fastlane ios release_candidate scheme:sandbox skip_version_update:true
          fi

      # - name: Notify Slack on Success
      #   if: success()
      #   run: |
      #     CURRENT_GITHUB_ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #     curl -X POST -H 'Content-type: application/json' --data "{\"attachments\":[{\"color\":\"#0000FF\",\"title\":\"[NATIVE] iOS Build Deployment Successful\", \"text\":\"Tag: ${{ github.ref_name }} (<$CURRENT_GITHUB_ACTION_RUN_URL|github action run url>)\"}]}" ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }}

      # - name: Notify Slack on Failure
      #   if: failure()
      #   run: |
      #     CURRENT_GITHUB_ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #     curl -X POST -H 'Content-type: application/json' --data "{\"attachments\":[{\"color\":\"#FF0000\",\"title\":\"[NATIVE] iOS Build Deployment Failed\", \"text\":\"<!subteam^S052B9WNGCV> Tag: ${{ github.ref_name }} (<$CURRENT_GITHUB_ACTION_RUN_URL|github action run url>)\"}]}" ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }}
