name: OTA Deployment

on:
  push:
    branches:
      - sanggggg/add-cd-sandbox

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SCC_FRONTEND_BUILD_CONFIGURATIONS_SSH_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get iOS version from Info.plist
        id: get_ios_version
        run: |
          IOS_VERSION=$(grep -A1 "<key>CFBundleShortVersionString</key>" ios/sccReactNative/Info.plist | grep "<string>" | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
          echo "IOS_VERSION=$IOS_VERSION" >> $GITHUB_ENV

      - name: Get Android version from version.properties
        id: get_android_version
        run: |
          ANDROID_VERSION=$(cat android/app/version.properties | grep version | cut -d'=' -f2)
          echo "ANDROID_VERSION=$ANDROID_VERSION" >> $GITHUB_ENV

      - name: Deploy iOS OTA
        run: yarn ota-deploy:sandbox -p ios -t ${{ env.IOS_VERSION }} -f

      - name: Deploy Android OTA
        run: yarn ota-deploy:sandbox -p android -t ${{ env.ANDROID_VERSION }} -f

      - name: Notify Slack on Success
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'scc-server'
          slack-message: |
            ✅ [DEV] Scc-App OTA Deployment Successful
            iOS Version: ${{ env.IOS_VERSION }}
            Android Version: ${{ env.ANDROID_VERSION }}
            Commit: ${{ github.sha }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }}

      - name: Notify Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'scc-server'
          slack-message: |
            ❌ [DEV] Scc-App OTA Deployment Failed
            iOS Version: ${{ env.IOS_VERSION }}
            Android Version: ${{ env.ANDROID_VERSION }}
            Check the workflow run for more details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }}